# Generated by Django 3.1.3 on 2021-02-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('ENSEIGNANT', 'Enseignant'), ('MEMBRE_SCOLARITE', 'Membre scolarite'), ('MEMBRE_FINANCE', 'Membre Finance'), ('GERANT_BIBLIOTHEQUE', 'Gerant Bibliotheque'), ('ADMIN', 'Admin'), ('DIRECTEUR_DE_L_ECOLE', "Directeur de l'école"), ('DIRECTEUR_DES_ETUDES', 'Directeur des études'), ('CHEF_DE_DEPARTEMENT', 'Chef de département'), ('ASSISTANT_CHEF_DEPARTEMENT', 'Assistant Chef département'), ('CHEF_SCOLARITE', 'Chef scolarité'), ('CHEF_SERVICE_ADMINISTRATIF', 'Chef Service administratif'), ('RESPONSABLE_CLASSE', 'Responsable classe'), ('RESPONSABLE_PEDAGOGIQUE', 'Responsable pédagogique'), ('PERSONNEL', 'Personnel'), ('MAINTENANCE', 'Maintenance'), ('RESPONSABLE_REX', 'Responsable Rex'), ('MAITRE_STAGE', 'Maitre Stage'), ('COMPTABLE', 'Comptable'), ('MEDECIN', 'Medecin'), ('COMMUNICATION', 'Communication'), ('ADMIN_BIBLIOTHEQUE', 'Admin Bibliotheque'), ('INGENIEUR', 'Ingenieur'), ('RESPONSABLE_PFE', 'Responsable PFE'), ('CORRECTEUR', 'Correcteur')], default='ETUDIANT', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
