# Generated by Django 3.1.14 on 2021-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210215_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], max_length=7),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('INGENIEUR', 'Ingenieur'), ('ADMIN', 'Admin'), ('MAITRE_STAGE', 'Maitre Stage'), ('INSTITUTION', 'Insitution')], default='ETUDIANT', max_length=100),
        ),
    ]
