# Generated by Django 3.1.3 on 2021-04-29 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210429_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(max_length=300)),
                ('nationalite', models.CharField(max_length=200)),
                ('pays_d_origine', models.CharField(max_length=250)),
                ('situation_matrimoniale', models.CharField(max_length=50, verbose_name='')),
                ('nbre_d_enfants', models.CharField(max_length=3)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.departement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
