# Generated by Django 3.2 on 2021-11-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vacataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('INGENIEUR', 'Ingenieur'), ('ADMIN', 'Admin'), ('MAITRE_STAGE', 'Maitre Stage')], default='ETUDIANT', max_length=100),
        ),
        migrations.DeleteModel(
            name='Vacataire',
        ),
    ]
