# Generated by Django 3.1.3 on 2021-11-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211115_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], max_length=7),
        ),
    ]
