# Generated by Django 3.1.3 on 2021-11-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211115_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('INGENIEUR', 'Ingenieur'), ('ADMIN', 'Admin'), ('MAITRE_STAGE', 'Maitre Stage'), ('INSTITUTION', 'insitution')], default='ETUDIANT', max_length=100),
        ),
    ]
